### ISSUE TITLE
Scoping: Working list of the additional frameworks views

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swift-extras#29]
Active list of all available views we will wrap. From:
- https://developer.apple.com/documentation/avkit
- https://developer.apple.com/documentation/authenticationservices
- https://developer.apple.com/documentation/corelocationui
- https://developer.apple.com/documentation/deviceactivity
- https://developer.apple.com/documentation/homekit
- https://developer.apple.com/documentation/mapkit
- https://developer.apple.com/documentation/musickit
- https://developer.apple.com/documentation/passkit
- https://developer.apple.com/documentation/photokit
- https://developer.apple.com/documentation/scenekit
- https://developer.apple.com/documentation/spritekit
- https://developer.apple.com/documentation/swiftcharts

Discussion on how and if a particular view will be implemented should happen within the associated issue not in this issue.

AVKit:
- [ ] [VideoPlayer](https://developer.apple.com/documentation/avkit/videoplayer) liveviewnative/liveview-client-swift-extras#28 

Authentication Services:
- [ ] [SigningWithAppleButton](https://developer.apple.com/documentation/authenticationservices/signinwithapplebutton)  liveviewnative/liveview-client-swift-extras#27 

CoreLocationUI:
- [ ] [LocationButton](https://developer.apple.com/documentation/corelocationui/locationbutton) liveviewnative/liveview-client-swift-extras#1

DeviceActivity:
- [ ] [DeviceActivityReport](https://developer.apple.com/documentation/deviceactivity/deviceactivityreport) liveviewnative/liveview-client-swift-extras#2

HomeKit:
- HMAccessory
    - [ ] [CameraView](https://developer.apple.com/documentation/homekit/cameraview) liveviewnative/liveview-client-swift-extras#3

MapKit:
- [ ] [Map](https://developer.apple.com/documentation/mapkit/map) liveviewnative/liveview-client-swift-extras#4

MusicKit:
- [ ] [ArtworkImage](https://developer.apple.com/documentation/musickit/artworkimage) liveviewnative/liveview-client-swift-extras#5

PassKit:
- ApplePay
    - [ ] [PayWithApplePayButton](https://developer.apple.com/documentation/passkit/paywithapplepaybutton) liveviewnative/liveview-client-swift-extras#6
- Wallet
    - [ ] [VerifyIdentityWithWalletButton](https://developer.apple.com/documentation/passkit/verifyidentitywithwalletbutton) liveviewnative/liveview-client-swift-extras#7
    - [ ] [AddPassToWalletButton](https://developer.apple.com/documentation/passkit/addpasstowalletbutton) liveviewnative/liveview-client-swift-extras#8

PhotoKit:
- [ ] [PhotosPicker](https://developer.apple.com/documentation/photokit/photospicker) liveviewnative/liveview-client-swift-extras#9

SceneKit:
- [ ] [SceneView](https://developer.apple.com/documentation/scenekit/sceneview) liveviewnative/liveview-client-swift-extras#10

SpriteKit:
- [ ] [SpriteView](https://developer.apple.com/documentation/spritekit/spriteview) liveviewnative/liveview-client-swift-extras#11

SwiftUI Charts:
- [x] [Chart](https://developer.apple.com/documentation/charts/chart) liveview-native/liveview-native-swiftui-charts/issues/1
- [x] [Plot](https://developer.apple.com/documentation/charts/plot) liveview-native/liveview-native-swiftui-charts/issues/2
- [ ] [AreaMark](https://developer.apple.com/documentation/charts/areamark) liveview-native/liveview-native-swiftui-charts/issues/3
- [ ] [LineMark](https://developer.apple.com/documentation/charts/linemark) liveview-native/liveview-native-swiftui-charts/issues/4
- [ ] [PointMark](https://developer.apple.com/documentation/charts/pointmark) liveview-native/liveview-native-swiftui-charts/issues/5
- [ ] [RectangleMark](https://developer.apple.com/documentation/charts/rectanglemark) liveview-native/liveview-native-swiftui-charts/issues/6
- [ ] [RuleMark](https://developer.apple.com/documentation/charts/rulemark) liveview-native/liveview-native-swiftui-charts/issues/7
- [x] [BarMark](https://developer.apple.com/documentation/charts/barmark) liveview-native/liveview-native-swiftui-charts/issues/8
- [ ] [AxisMark](https://developer.apple.com/documentation/charts/axismarks) liveview-native/liveview-native-swiftui-charts/issues/9
- [ ] [AxisTick](https://developer.apple.com/documentation/charts/axistick) liveview-native/liveview-native-swiftui-charts/issues/10
- [ ] [AxisGridLine](https://developer.apple.com/documentation/charts/axisgridline) liveview-native/liveview-native-swiftui-charts/issues/11
- [ ] [AxisValueLabel](https://developer.apple.com/documentation/charts/axisvaluelabel) liveview-native/liveview-native-swiftui-charts/issues/12
- [ ] [NumberBins](https://developer.apple.com/documentation/charts/numberbins) liveview-native/liveview-native-swiftui-charts/issues/13
- [ ] [DateBins](https://developer.apple.com/documentation/charts/datebins) liveview-native/liveview-native-swiftui-charts/issues/14
- [ ] [BasicChartSymbolShape](https://developer.apple.com/documentation/charts/basicchartsymbolshape) liveview-native/liveview-native-swiftui-charts/issues/15

**Comment by AZholtkevych** [comment]
FYI @AZholtkevych
